# Generated by Django 2.2.12 on 2022-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('number', models.CharField(max_length=16)),
                ('qualification', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('ug', 'ug'), ('pg', 'pg')], default=0, max_length=4)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('message', models.TextField()),
            ],
        ),
    ]
